name: The Elemental Bakery
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2e65c2'
    - '#111111'
    - '#a6a8b7'
    - '#ca1d3b'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
