name: Godai Elemental Bakery
favicon: null
layout_spectrum: 0.49904
typography_spectrum: 0.42639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f0f2'
    - '#12110b'
    - '#7b92a9'
    - '#d1614d'
    - '#c0b8bc'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
