name: Godai Elemental Bakery
favicon: null
layout_spectrum: 0.49904
typography_spectrum: 0.42639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1215'
    - '#d7c2a5'
    - '#fafbf5'
    - '#967e62'
    - '#405b76'
  brandStrength: 1
  lightness: 0.37044887780211866
  saturation: 0.125
  rhythmicContrast: 0.2538994166534394
purpose: []
