name: Godai Elemental Bakery
favicon: null
layout_spectrum: 0.2432
typography_spectrum: 0.46299695409834385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6339650840964168
  lightness: 0.37044887780211866
  saturation: 0.164744469569996
  rhythmicContrast: 0.2538994166534394
purpose: []
